version: '3.7'
services:

  db:
    image: postgres:latest
    container_name: "scaffold-db"
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - DB_USER=$DBUSER
      - DB_PASSWORD=3190d261d186aeead3a8deec202737c7775af5c8d455a9e5ba958c48b5fd3f59
      - DB_DATABASE=$DATABASE
      - POSTGRES_PASSWORD=264c0424e4bd463a7d02b9db6896143e1a96cd1c52511119f839d2bc9c934241
      - POSTGRES_USER=postgres
    volumes:
      - ${PWD}/deploy/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - pg_db:/var/lib/postgresql/data

  server:
    image: server:latest
    container_name: "scaffold-server"
    restart: 'always'
    links:
      - db
      - storage
    depends_on:
      - db
      - storage
    ports:
      - "12000:12000"

  storage:
    image: minio/minio:latest
    container_name: "scaffold-file-storage"
    restart: 'always'
    ports:
      - '9000:9000'
    volumes:
      - minio_data:/data
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data

volumes:
  pg_db: {}
  minio_data: {}
# vim: et:sw=2